name: Update package-lock.json

on:
  push:
    branches: [master]
    paths: ["package.json", ".github/workflows/update-lockfile.yml"]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository for source branch
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
    - name: Update lockfile
      run: |
        npm install --package-lock-only
        npm audit fix
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.2.1
      with:
        add: package*.json
        message: Update dependencies ${{ github.sha }}
